title: "Buttons"
description: |
  Buttons can be used to lead users to a different link or to activate something.

patterns:
    basic:
      title: "Basic"
      description: |
        The basic button should be used for all standard call-to-actions.
      fields:
        - name: link
          type: string
          example: "/#/"
        - name: name
          type: string
          example: "Btn Basic"
    ghost:
      title: "Ghost"
      description: |
        The ghost button should be used next to the basic button if two buttons are next to each other.
      fields:
        - name: link
          type: string
          example: "/#/"
        - name: name
          type: string
          example: "Btn Ghost"
    add:
      title: "Add"
      description: |
        The add button is used when adding selections on the profile page.
    account:
      title: "Account"
      description: |
        The account button should be used on the settings page to access the account settings.
      fields:
        - name: link
          type: string
          example: "#one"
        - name: name
          type: string
          example: "Account"
    connections:
      title: "Connections"
      description: |
        The connections button should be used on the settings page to access connection settings.
      fields:
        - name: link
          type: string
          example: "#two"
        - name: name
          type: string
          example: "Connections"
    discover:
        title: "Discover"
        description: |
          The discover button should be used on the settings page to access the friend finder settings.
        fields:
          - name: link
            type: string
            example: "#three"
          - name: name
            type: string
            example: "Discover"
