title: "Icon Sets"
description: |
  For miscellaneous icons that go together.

patterns:
    icon-inline:
      title: "Icon Sets"
      description: |
        The icon sets is for the icons on the profile cards.
    platform:
      title: "Platform Label"
      description: |
        The platform label is for users to select their platforms.
      fields:
        - name: platform
          type: string
          example: "Nintendo Switch"
    genre:
      title: "Game Genre Label"
      description: |
        The game genre label is for users to select their platforms.
      fields:
        - name: genre
          type: string
          example: "Strategy"
        - name: icon
          type: string
          example: "/images/icons.svg#strat-icon"
