title: "Navigations"
description: |
  Navigations are navs for sections other then the header.

patterns:
  nav-profile-buttons:
    title: "Profile Buttons"
    description: |
      These buttons are for navigation to the edit state and settings.
  nav-profile-save:
    title: "Profile Save Button"
    description: |
      This navigation is formatted for the profile edit page on small sizes.
  nav-settings:
    title: "Settings Navigation"
    description: |
      This navigation is used to move within the subsections of the settings page.
