title: "Sections"
description: |
  Sections can be used to group and separate content.

patterns:
    image-banner:
      title: "Image Banner"
      description: |
        The image banner section is used on both the profile and the discover page.
      fields:
        - name: image
          type: string
          example: "/images/placeholder-banner.jpg"
        - name: alt
          type: string
          example: "Accessibility stuff"
    section-banner-profile:
      title: "Profile Banner"
      description: |
        The Profile Banner is used on the profile page to display the users cover photo and profile picture.
    section-banner-discover:
      title: "Discover Banner"
      description: |
        The Discover Banner is used on the Discover page as an intro to the section.
    section-discover-profile:
      title: "Discover Profiles Section"
      description: |
        The Discover Banner is used on the Discover page as an intro to the section.
    section-profile-display:
      title: "Profile Display"
      description: |
        The Profile Display section is used for the viewing section of the profile page.
      fields:
        - name: name
          type: string
          example: "George Micheal"
        - name: age
          type: string
          example: "26"
        - name: timezone
          type: string
          example: "Eastern Time"
        - name: type
          type: string
          example: "Commander"
    section-banner-dashboard:
      title: "Dashboard Profiles Section"
      description: |
        The Dashboard Banner is used on the Dashboard page as an intro to the section.
    section-banner-profile-edit:
      title: "Profile Banner Edit"
      description: |
        The Profile Banner Edit is used on the edit state of the profile page.
