title: "Cards"
description: |
  Cards can be used to group and separate content.

patterns:
  image:
    title: "Image Card"
    description: |
      The image card should be used for profile pictures only.
    width: 15em
  card-image-edit:
    title: "Image Card Edit"
    description: |
      The image card edit should only be used during the profile settings.
    width: 15em
  profile:
    title: "Profile Card"
    description: |
      The profile card should be used to group content with the image card on the discover page.
    fields:
      - name: name
        type: string
        example: "Bob Burberry"
      - name: bio
        type: string
        example: "Something Bioish"
  card-profile-discover:
    title: "Full Profile Card"
    description: |
      The profile card should be used to group content with the image card on the discover page.
  games:
    title: "Game Card"
    description: |
      The game card should be used for the top 3 games that the user wants.
    fields:
      - name: image
        type: string
        example: "placeholder-banner.jpg"
      - name: game
        type: string
        example: "I'm a long game title"
