title: "Cards"
description: |
  Cards can be used to group and separate content.

patterns:
    image:
      title: "Image Card"
      description: |
        The image card should be used for profile pictures only.
      fields:
        - name: name
          type: string
          example: "Bob Burberry"
        - name: error
          type: string
          example: "You need to enter some text"
      width: 15em
    profile:
      title: "Profile Card"
      description: |
        The profile card should be used to group content with the image card on the discover page.
